version: '3.4'

services:
    nginx:
        image: nginx:1.13.7
        container_name: nginx
        depends_on:
            - flask
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
            - ./selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
        networks:
            - my-network
        ports:
            - 80:80
    flask:
        build:
            context: ./
            dockerfile: Dockerfile
        image: web
        container_name: flask
        networks:
            my-network:
                aliases:
                    - flask-app
        ports:
            - 8080:5000

networks:
    my-network: